# Generated by Django 6.1.1 on 2026-09-10 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('customer_name', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending verification'), ('approved', 'Verified'), ('paid', 'Paid'), ('disputed', 'Disputed'), ('voided', 'Voided'), ('refunded', 'Refunded')], default='draft', max_length=12)),
                ('total', models.IntegerField(default=0)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=20)),
                ('dispute_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('owner_pin', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('price_monthly', models.IntegerField()),
                ('price_annual', models.IntegerField()),
                ('monthly_verified_bills', models.IntegerField()),
                ('max_staff', models.IntegerField()),
                ('tagline', models.CharField(blank=True, max_length=120)),
                ('is_target', models.BooleanField(default=False)),
                ('features', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('created', 'Bill created'), ('edited', 'Bill edited'), ('scanned', 'Customer scanned QR'), ('verified', 'Customer verified bill'), ('disputed', 'Customer disputed bill'), ('paid', 'Payment recorded'), ('voided', 'Bill voided'), ('refunded', 'Bill refunded')], max_length=12)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.bill')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('price', models.IntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.bill')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='core.business'),
        ),
        migrations.AddField(
            model_name='business',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plan'),
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('role', models.CharField(default='staff', max_length=20)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='core.business')),
            ],
            options={
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BillEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=80)),
                ('old_price', models.IntegerField()),
                ('new_price', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='core.bill')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staffmember')),
            ],
            options={
                'ordering': ['at'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.staffmember'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('default_price', models.IntegerField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.business')),
            ],
            options={
                'unique_together': {('business', 'name')},
            },
        ),
    ]
