# Generated by Django 6.1.1 on 2026-09-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='accent',
            field=models.CharField(default='blush', max_length=10),
        ),
        migrations.AddField(
            model_name='business',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='tagline',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='business',
            name='thank_you',
            field=models.CharField(default='Thank you for choosing us ♡', max_length=150),
        ),
    ]
