# Generated by Django 6.1.1 on 2026-09-13 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_business_accent_business_location_business_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='plan_paid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('amount', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout')], default='pending', max_length=10)),
                ('checkout_request_id', models.CharField(max_length=64, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=64)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=20)),
                ('result_desc', models.CharField(blank=True, max_length=255)),
                ('extends_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mpesa_payments', to='core.business')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
