# Generated by Django 6.1.1 on 2026-09-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_staffinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_ref',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
