# Generated by Django 6.1.1 on 2026-09-19 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_bill_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='core.bill'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_ref', ''), _negated=True), fields=('payment_ref',), name='uniq_bill_payment_ref'),
        ),
        migrations.AddConstraint(
            model_name='mpesapayment',
            constraint=models.UniqueConstraint(condition=models.Q(('mpesa_receipt', ''), _negated=True), fields=('mpesa_receipt',), name='uniq_mpesapayment_receipt'),
        ),
    ]
