# Generated by Django 6.1.1 on 2026-09-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_auditevent_bill_bill_uniq_bill_payment_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='owner_pin',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staffinvite',
            name='created_by_pin',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staffinvite',
            name='staff_pin',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='staff_pin',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
