"use client";

import { useEffect, useState } from "react";
import Image from "next/image";
import { api, Bill } from "@/lib/api";
import { Receipt } from "@/app/receipt";
import { MpesaTrustStrip } from "@/app/mpesa";
import { BrandLoader } from "@/app/loading-state";

/* Public authenticity page — anyone with the code (or the QR on a printed
   receipt) can confirm a receipt is genuine. No business header needed. */
export default function PublicReceipt({ params }: { params: Promise<{ code: string }> }) {
  const [bill, setBill] = useState<Bill | null>(null);
  const [missing, setMissing] = useState(false);

  useEffect(() => {
    params.then((p) => api.getBill(p.code).then(setBill).catch(() => setMissing(true)));
  }, [params]);

  if (missing)
    return (
      <main className="mx-auto max-w-md px-5 py-20 text-center">
        <Image src="/favicon.png" alt="SaloonOS" width={56} height={56} className="mx-auto h-14 w-14 rounded-2xl" />
        <h1 className="font-display mt-3 text-2xl font-bold">No such receipt</h1>
        <p className="mt-2 text-sm text-dim">
          If you were given this link, double-check the receipt number with the salon.
        </p>
      </main>
    );

  if (!bill) return <BrandLoader label="Checking your verified receipt…" />;

  return (
    <main className="mx-auto max-w-md px-4 py-8">
      <p className="mb-4 flex items-center justify-center gap-2 text-[11px] font-semibold uppercase tracking-[0.3em] text-dim">
        <Image src="/favicon.png" alt="" width={20} height={20} className="h-5 w-5 rounded-md" />
        SaloonOS · receipt lookup
      </p>
      <Receipt branding={bill.business} bill={bill} variant="public" />
      {bill.status === "paid" && (
        <MpesaTrustStrip note={bill.payment_method?.includes("M-Pesa")
          ? `Paid via M-Pesa${bill.payment_ref ? ` · receipt ${bill.payment_ref}` : ""} — confirmed by Safaricom.`
          : "M-Pesa payments are confirmed by Safaricom with an SMS receipt."} />
      )}
      <div className="card mt-4 p-4 text-center text-xs text-dim">
        This page is generated by SaloonOS directly from the salon&apos;s records.
        If it shows <b>✓ Customer verified</b>, the customer confirmed these exact
        services and prices on their own phone.
      </div>
    </main>
  );
}
